In [1]:
%load_ext jupyter_ai_magics

In [10]:
from datascience import *
import numpy as np

## Data Types

Every value has a type, and the built-in `type` function returns the type of the result of any expression. Suggested Reading: https://inferentialthinking.com/chapters/04/Data_Types.html.

In [3]:
type(5)

int

In [5]:
type("banana")

str

In [4]:
type(abs)

builtin_function_or_method

Most of the data you will encounter will either be textual (strings) or numerical (integers/floats). 

#### Numbers

Integers are called `int` values in the Python language. They can only represent whole numbers (negative, zero, or positive) that don’t have a fractional component.

Real numbers are called `float` values (or floating point values) in the Python language. They can represent whole or fractional numbers but have some limitations.

In [9]:
# Some int values
print(2)
print(2+3)
print(type(3))

2
5
<class 'int'>


In [8]:
# Some float values
print(1.5)
print(2.0)
print(type(1/3))

1.5
2.0
<class 'float'>


#### Strings 

A piece of text represented in a computer is called a string. A string can represent a word, a sentence, or even the contents of every book in a library. Since text can include numbers (like this: 5) or truth values (True), a string can also describe those things.

In [10]:
"data" + "science"

'datascience'

The `str` function returns a string representation of any value

In [12]:
"That's " + str(1 + 1) + ' ' + str(True)

"That's 2 True"

You just saw we converted an integer value (1+1) and a Boolean value (True) to string! You can also convert float to int and int to float similarly. This is simply done by specifying a type on to a variable. Read more about it https://www.w3schools.com/python/python_casting.asp. 

In [6]:
int(2.0)

2

In [7]:
int(2.6) # you lose information here

2

In [8]:
float(2)

2.0

##### chatgpt time! 
Now let's ask chatgpt about strings and numbers in Python!

In [16]:
%%ai openai-chat:gpt-3.5-turbo
What are data types in Python? Explain it like you would to a 5 year old. What are numbers and strings in Python?

In Python, data types are like different kinds of things we can have. It's a way to group similar things together. 

Numbers in Python are just like numbers we use in math. They can be whole numbers (like 1, 2, 3) or numbers with decimal points (like 1.5, 2.8, 3.9). We can do math operations with numbers in Python, like adding, subtracting, multiplying or dividing them.

Strings in Python are like a bunch of letters or words put together. They are written in quotes, like "hello" or "apple". We can think of them as a string of characters. We can do different things with strings, like joining them together, finding certain letters, or even changing some of the letters. 

So, in simple words, numbers in Python are for doing math and strings are for working with words and letters.

#### String methods

Just like you're familiar with arithmetic operations on numbers, we are now going to look at methods that can be applied on strings!

###### upper/lower
`upper` generates an upper cased version of a string and `lower` generates a lower cased version of a string.

In [18]:
"loud".upper()

'LOUD'

In [19]:
"LOUD".lower()

'loud'

###### replace 
`replace` replaces ALL instances of a substring within the string.

In [22]:
'hitchhiker'.replace('hi', 'ma')

'matchmaker'

##### chatgpt time! 
Let's ask chatgpt to explain string methods!

In [23]:
%%ai openai-chat:gpt-3.5-turbo
What are string methods in Python? Give me some very simple examples.

String methods in Python are special actions or functions that we can perform on strings to do different things. They help us manipulate and work with strings in interesting ways. Here are a few simple examples of string methods:

1. `upper()` - This method makes all the letters in a string uppercase:
   ```python
   name = "john"
   print(name.upper())  # Output: JOHN
   ```

2. `lower()` - This method makes all the letters in a string lowercase:
   ```python
   message = "Hello World"
   print(message.lower())  # Output: hello world
   ```

3. `replace()` - This method replaces specific parts of a string with something else:
   ```python
   sentence = "I like apples"
   new_sentence = sentence.replace("apples", "bananas")
   print(new_sentence)  # Output: I like bananas
   ```

4. `count()` - This method counts the number of times a specific word or letter appears in a string:
   ```python
   sentence = "I have three dogs"
   count_dogs = sentence.count("dogs")
   print(count_dogs)  # Output: 1
   ```

These are just a few examples of string methods in Python. There are many more useful methods that can help us work with strings effectively.

Now let's try out one of the examples from chatgpt's response! See from the cell below that `count` indeed counts the number of occurrences of a specific word/letter and the output matches what the response above shows.

In [31]:
sentence = "I have three dogs"
count_dogs = sentence.count("dogs")
print(count_dogs)  # Output: 1

1


## Comparisons

Python includes a variety of operators that compare values. The result of a comparison is often a `Boolean` value (e.g., `True` or `False`). This concept will be very useful when we learn about conditional statements!

In [25]:
3 > 1 + 1

True

In [26]:
1 < 1 + 1 < 3

True

In [27]:
# Strings can also be compared, and their order is alphabetical. A shorter string is less than a longer string that begins with the shorter string.
"Dog" > "Catastrophe" > "Cat" 

True

##### chatgpt time! 
Let's ask chatgpt for some more examples of comparison operators!

In [30]:
%%ai openai-chat:gpt-3.5-turbo
Give me some very simple examples of comparison operators in Python and their usage that results in True and False values. Display the output in a tabular form.

Certainly! Here are some simple examples of comparison operators in Python, along with their usage and the resulting `True` or `False` values:

| Operator | Description                 | Example                 | Result |
|----------|-----------------------------|-------------------------|--------|
| `==`     | Equality                    | `5 == 5`                | True   |
| `!=`     | Inequality                  | `3 != 7`                | True   |
| `>`      | Greater than                | `10 > 8`                | True   |
| `<`      | Less than                   | `6 < 3`                 | False  |
| `>=`     | Greater than or equal to    | `4 >= 4`                | True   |
| `<=`     | Less than or equal to       | `9 <= 7`                | False  |

These are some of the common comparison operators used in Python to compare values. When the comparison is true, it evaluates to `True`, and when the comparison is false, it evaluates to `False`.

## Arrays 

Values can be grouped together into collections, and by grouping values together, we can write code that performs a computation on many pieces of data at once! We will mainly work with arrays in this class. Suggested Reading: https://inferentialthinking.com/chapters/05/Sequences.html

An array in Python contains a sequence of values which have the same type. A column of a table is also an array!

Calling the function `make_array` on several values places them into an array, which is a kind of sequential collection.

In [35]:
english_parts_of_speech = make_array("noun", "pronoun", "verb", "adverb", "adjective", "conjunction", "preposition", "interjection")
english_parts_of_speech

array(['noun', 'pronoun', 'verb', 'adverb', 'adjective', 'conjunction',
       'preposition', 'interjection'],
      dtype='<U12')

In [4]:
array_of_numbers = make_array(7,5,3,1)
array_of_numbers

array([7, 5, 3, 1])

##### item
You can access an element of an array using `item` method

In [7]:
array_of_numbers.item(0) # Remember in Python, arrays are 0 indexed!

7

In [6]:
array_of_numbers.item(2)

3

##### chatgpt time! 
Let's work with chatgpt to understand arrays!

In [2]:
%%ai openai-chat:gpt-3.5-turbo
What are arrays in Python? Explain it like you would to a 5 year old. Give me a very simple example.

Arrays in Python are like containers that hold a bunch of things, just like a box that can store many toys. Imagine you have a box of fruits, that is an array. Each fruit is like an element in the array. For example, let's say you have an array of three fruits: apple, banana, and orange. So, it would look something like this:

`fruits = ["apple", "banana", "orange"]`

The array 'fruits' holds these three fruits. It helps us organize and keep track of these fruits easily, just like putting all your toys in a box.

#### Functions on Arrays
We can manipulate all the entries in an array at once using some functions in Python (for example, using some functions in a package called `numpy`)!

##### diff
`diff` function computes the difference between each adjacent pair of elements in an array.

In [41]:
np.diff(array_of_numbers)

array([-2, -2, -2])

##### sum
`sum` adds all elements of an array together.

In [42]:
np.sum(array_of_numbers)

16

##### chatgpt time! 
Let's work with chatgpt to understand different functions on arrays!

In [8]:
%%ai openai-chat:gpt-3.5-turbo
Give me some very simple examples of different numpy reference functions (in a tabular form) that take an array as an argument and return a single value or an array of values. 

Certainly! Here's a table of numpy reference functions that take an array as an argument and return a single value or an array of values, along with very simple examples:

| Function                   | Description                                                          | Example                                      |
|----------------------------|----------------------------------------------------------------------|----------------------------------------------|
| `np.sum()`                 | Calculate the sum of array elements                                   | `total = np.sum(arr)`                         |
| `np.mean()`                | Calculate the mean (average) of array elements                        | `avg = np.mean(arr)`                          |
| `np.max()`                 | Find the maximum value in the array                                    | `maximum = np.max(arr)`                       |
| `np.min()`                 | Find the minimum value in the array                                    | `minimum = np.min(arr)`                       |
| `np.sort()`                | Sort the elements of an array in ascending order                      | `sorted_arr = np.sort(arr)`                    |
| `np.argmax()`              | Find the index of the maximum value in the array                       | `index_max = np.argmax(arr)`                   |
| `np.argmin()`              | Find the index of the minimum value in the array                       | `index_min = np.argmin(arr)`                   |
| `np.unique()`              | Find the unique values in the array                                    | `unique_vals = np.unique(arr)`                 |
| `np.where()`               | Find the indices where a condition is met                              | `indices = np.where(arr > 5)`                  |
| `np.any()`                 | Check if any element in the array satisfies a condition                | `result_any = np.any(arr > 5)`                 |
| `np.all()`                 | Check if all elements in the array satisfy a condition                 | `result_all = np.all(arr > 5)`                 |
| `np.cumsum()`              | Calculate the cumulative sum of array elements                         | `cumulative_sum = np.cumsum(arr)`              |
| `np.cumprod()`             | Calculate the cumulative product of array elements                     | `cumulative_prod = np.cumprod(arr)`            |
| `np.diff()`                | Calculate the difference between consecutive elements in the array     | `differences = np.diff(arr)`                   |
| `np.exp()`                 | Calculate the exponential of each element in the array                 | `exp_arr = np.exp(arr)`                        |
| `np.log()`                 | Calculate the natural logarithm of each element in the array           | `log_arr = np.log(arr)`                        |
| `np.sqrt()`                | Calculate the square root of each element in the array                 | `sqrt_arr = np.sqrt(arr)`                      |

These functions can be used to perform calculations, obtain statistical information, and carry out element-wise operations on arrays to obtain desired outputs.

##### arange
A range is an array of numbers in increasing or decreasing order, each separated by a regular interval. Ranges are defined using the `arange` function, which takes either one, two, or three arguments: a 'start', an 'end', and a ‘step’.

If you pass one argument to `arange`, this becomes the end value, with start=0, step=1 assumed. Two arguments give the start and end with step=1 assumed. Three arguments give the start, end and step explicitly.

A range always includes its start value, but does not include its end value. It counts up by step, and it stops before it gets to the end.

In [14]:
np.arange(5) # assumes start=0 and step=1

array([0, 1, 2, 3, 4])

In [15]:
np.arange(3, 9) # assumes step=1

array([3, 4, 5, 6, 7, 8])

In [16]:
np.arange(3, 30, 5)

array([ 3,  8, 13, 18, 23, 28])

##### append
You can append to an array using `append` method.

In [13]:
my_array = np.arange(1,30,5)
my_array

array([ 1,  6, 11, 16, 21, 26])

In [16]:
# Note that this will not change the original array! Assign it to a new array variable if you want to keep the changes!
np.append(my_array, 30) # arguments to append are the array you want to append the value to followed by the value

array([ 1,  6, 11, 16, 21, 26, 30])

In [19]:
np.append(my_array, make_array(30, 34)) # you can append multiple values including an array!

array([ 1,  6, 11, 16, 21, 26, 30, 34])